spring.application.name=reviewlens

server.address=0.0.0.0
server.port=${PORT:8080}
server.forward-headers-strategy=framework

# =========================
# Database
# =========================
spring.datasource.url=${DB_URL:jdbc:postgresql://reviewlens-db.ctmwm0aq6j3g.us-west-2.rds.amazonaws.com:5432/postgres?sslmode=require}
spring.datasource.username=${DB_USERNAME:reviewlens}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

# =========================
# Actuator
# =========================
management.endpoints.web.exposure.include=health,info

# =========================
# GitHub OAuth2
# =========================
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET}
spring.security.oauth2.client.registration.github.scope=read:user,user:email
spring.security.oauth2.client.registration.github.redirect-uri=${GITHUB_REDIRECT_URI:http://localhost:5173/login/oauth2/code/{registrationId}}

# =========================
# Frontend
# =========================
reviewlens.frontend-url=${FRONTEND_URL:http://localhost:5173}

# =========================
# AWS Bedrock
# =========================
reviewlens.ai.bedrock.model-id=${BEDROCK_MODEL_ID:us.anthropic.claude-sonnet-4-6}

# =========================
# AWS S3
# =========================
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:reviewlens-xingranma-reports}
aws.region=${AWS_REGION:us-west-2}

# =========================
# Error Messages
# =========================
server.error.include-message=always
server.error.include-binding-errors=always