package com.reviewlens.dto;

import java.util.List;

/**
 * Represents the structured result generated by the AI code reviewer.
 *
 * @param summary         overall assessment of the repository
 * @param strengths       positive aspects found in the codebase
 * @param risks           important maintainability, reliability, or security
 *                        concerns
 * @param recommendations recommended improvements
 */
public record AiReviewResult(
        String summary,
        List<String> strengths,
        List<String> risks,
        List<String> recommendations) {
}