CREATE TABLE reviews (
    id BIGSERIAL PRIMARY KEY,
    repository_url VARCHAR(500) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);